# Generated by Django 3.0.2 on 2020-01-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.TextField()),
                ('name', models.CharField(max_length=32)),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('code_type', models.CharField(choices=[('plain_text', 'Text'), ('email', 'Email'), ('href', 'Link')], max_length=100)),
                ('background_color', models.CharField(max_length=16)),
                ('foreground_color', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
    ]
