# Generated by Django 3.0.2 on 2020-01-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('browser', models.CharField(max_length=64)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_manager.QrCode')),
            ],
        ),
    ]
