# Generated by Django 3.0.2 on 2020-01-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_manager', '0002_qrstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrstats',
            name='browser',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
