# Generated by Django 3.0.2 on 2020-01-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_manager', '0003_auto_20200118_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=16),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='foreground_color',
            field=models.CharField(default='#000000', max_length=16),
        ),
    ]
